[package]
name = "lerpz_invoice"
version = "0.1.0"
edition = "2021"
authors = ["Kasper Jønsson"]
repository = "https://github.com/kanerix/rust-python-project-template"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
